### ISSUE TITLE
DeviceName

### ISSUE THREAD

**Issue by ua0lnj** [vdr-projects/vdr-plugin-mcli#15]
How about add DeviceName in device.c?

cString cMcliDevice::DeviceName(void) const
{
if (!m_enable) {
#ifdef DEBUG_RESOURCES
DEBUG_MASK(DEBUG_BIT_RESOURCES,
dsyslog("mcli::%s: m_fetype=%d not enabled", __FUNCTION__, m_fetype);
)
#endif
return "";
}; 
return cString::sprintf("%s %d", "netceiver", CardIndex () + 1);
}

**Comment by pbiering** [comment]
@ua0lnj : can you please test the linked PR whether it fits your needs?

**Comment by ua0lnj** [comment]
I do not have a netceiver. But I use device name in channelscan plugin, for tuner detection.

**Comment by ua0lnj** [comment]
And, as I think, need to add this function to device.h

device.c:1192:9: error: no declaration matches ‘cString cMcliDevice::DeviceName() const’
 1192 | cString cMcliDevice::DeviceName(void) const
      |         ^~~~~~~~~~~
device.c:1192:9: note: no functions named ‘cString cMcliDevice::DeviceName() const’
In file included from device.c:20:
device.h:21:7: note: ‘class cMcliDevice’ defined here
   21 | class cMcliDevice:public cDevice
      |       ^~~~~~~~~~~
make[2]: *** [Makefile:90: device.o] Error 1
make[1]: *** [Makefile:75: plugin] Error 2

UPD.
In device.h need add too:

#if VDRVERSNUM >= 10728
       virtual cString DeviceName(void) const;
#endif

Then everything compiles.

**Comment by pbiering** [comment]
the missing/required extension of device.h was already detected by me and is included in the  PR
https://github.com/vdr-projects/vdr-plugin-mcli/pull/16/files

**Comment by pbiering** [comment]
PR merged into master
