### ISSUE TITLE
LOCK_THREAD

### ISSUE THREAD

**Issue by 9000h** [vdr-projects/vdr-plugin-mcli#7]
https://github.com/vdr-projects/vdr-plugin-mcli/blob/d4997d6e6a55dd515b7eb9641473600036d25669/filter.c#L286
found on MLD forum, is this the better solution
https://www.minidvblinux.de/forum/index.php?topic=9526.0

**Comment by pbiering** [comment]
fixed by https://github.com/vdr-projects/vdr-plugin-mcli/pull/8 - only 2 leftovers found beside the Makefile patch, which would need a bigger review

**Comment by 9000h** [comment]
hmm, but for newer versions the Unlock() below the LOCK_THREAD is still needed?

**Comment by pbiering** [comment]
good point, was not included in MLD patches...fixed by https://github.com/vdr-projects/vdr-plugin-mcli/pull/9
